[package]
name = "engine_rs"
version = "0.1.0"
authors = ["Seiji Emery <seijiemery@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.14.3"
specs-derive = "*"
serde = "1.0.91"
glium = "*"
glutin = "*"
cgmath = "*"
spin_sleep = "0.3.7"
